/* CSS */
import 'normalize.css'
import './scss/fonts.scss'
import './scss/common.scss'
import './scss/header.scss'
import './scss/drawer.scss'
import './scss/home.scss'
import './scss/about.scss'
import './scss/modal.scss'
import './scss/pagination.scss'
import './scss/accordion.scss'
import './scss/projects.scss'
import './scss/services.scss'
import './scss/articles.scss'

/* JS */
import './js/modal.js'
import './js/drawer.js'
import './js/header.js'
import './js/accordion.js'
import './js/projects.js'
